[tool]
[tool.poetry]
name = "DTOUserBot_Deployer"
version = "1.0"
description = "Automatic Deploy DTOUserBot to Heroku"
authors = ["Ümüd Məmmədov <@umudmmmdov1>"]
[tool.poetry.dependencies]
python = "^3.8"
bs4 = "*"
gitpython = "*"
heroku3 = "*"
requests = "*"
rich = "*"
telethon = "*"
